CREATE TABLE IF NOT EXISTS clientes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  razao_social TEXT NOT NULL,
  nome_fantasia TEXT,
  cnpj TEXT,
  email TEXT,
  telefone TEXT,
  endereco TEXT,
  cidade TEXT,
  estado TEXT,
  contato_principal TEXT,
  created_date TIMESTAMPTZ DEFAULT NOW(),
  updated_date TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS propostas (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  numero TEXT,
  revisao TEXT DEFAULT '00',
  cliente_id UUID REFERENCES clientes(id) ON DELETE SET NULL,
  cliente_nome TEXT,
  contato TEXT,
  referencia TEXT,
  titulo TEXT NOT NULL,
  tipo_fornecimento TEXT,
  valor_total NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'rascunho',
  data_proposta DATE,
  data_validade DATE,
  validade_texto TEXT,
  condicoes_pagamento TEXT,
  prazo_entrega TEXT,
  observacoes TEXT,
  reajuste TEXT,
  impostos TEXT,
  garantia TEXT,
  escopo TEXT,
  fora_escopo TEXT,
  ensaios TEXT,
  tratamento TEXT,
  databook TEXT,
  transporte TEXT,
  documentos TEXT,
  documentos_data DATE,
  itens JSONB DEFAULT '[]',
  created_date TIMESTAMPTZ DEFAULT NOW(),
  updated_date TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS romaneios (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  numero TEXT,
  proposta_id UUID REFERENCES propostas(id) ON DELETE SET NULL,
  proposta_numero TEXT,
  cliente_nome TEXT,
  data_emissao DATE,
  data_entrega DATE,
  status TEXT DEFAULT 'pendente',
  endereco_entrega TEXT,
  observacoes TEXT,
  itens JSONB DEFAULT '[]',
  created_date TIMESTAMPTZ DEFAULT NOW(),
  updated_date TIMESTAMPTZ DEFAULT NOW()
);
